[project]
authors = ["Petrus Hyv√∂nen <petrus.hyvonen@gmail.com>"]
channels = ["conda-forge/label/qgis_ltr", "conda-forge"]
description = "Add a short description here"
name = "pixi-qgis"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
qgis = ">=3.40.8,<4"
poppler = ">=24.12.0,<25"
scikit-learn = ">=1.7.0,<2"
pandas = ">=2.3.1,<3"
numpy = ">=2.3.1,<3"
matplotlib = ">=3.10.3,<4"
plotly = ">=6.2.0,<7"
onnxruntime = ">=1.22.0,<2"
shapely = ">=2.1.1,<3"
openpyxl = ">=3.1.5,<4"
