[workspace]
authors = ["Petrus Hyv√∂nen <petrus.hyvonen@gmail.com>"]
channels = ["conda-forge/label/qgis_ltr", "conda-forge"]
description = "Add a short description here"
name = "pixi-qgis"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
qgis = "qgis"

[dependencies]
qgis = ">=3.40.11,<4"
poppler = ">=25.7.0,<26"
scikit-learn = ">=1.7.2,<2"
pandas = ">=2.3.3,<3"
numpy = ">=2.3.5,<3"
matplotlib = ">=3.10.8,<4"
plotly = ">=6.5.0,<7"
onnxruntime = ">=1.22.0,<2"
shapely = ">=2.1.2,<3"
openpyxl = ">=3.1.5,<4"
